import type { Metadata } from "next";
import { Inter, Noto_Sans_Devanagari, Comic_Neue, Roboto } from "next/font/google";
import { LanguageProvider } from "@/contexts/LanguageContext";
import { AuthProvider } from "@/contexts/AuthContext";
import { AppShell } from "@/components/layout/AppShell";
import { PerfInit } from "@/components/PerfInit";
import { A11ySkipLink } from "@/components/A11ySkipLink";
import { InstallPrompt } from "@/components/InstallPrompt";
import { ConsentBanner } from "@/components/ConsentBanner";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
  preload: true,
  fallback: ["system-ui", "arial"],
});

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
  display: "swap",
  weight: ["400", "500", "700"],
  fallback: ["system-ui", "arial"],
});

const comicNeue = Comic_Neue({
  subsets: ["latin"],
  variable: "--font-comic",
  display: "swap",
  weight: ["400", "700"],
  fallback: ["system-ui", "cursive"],
});

const notoSansDevanagari = Noto_Sans_Devanagari({
  subsets: ["devanagari"],
  variable: "--font-hindi",
  display: "swap",
  preload: false, // Only preload for Hindi users (detected at runtime)
  weight: ["400", "600", "700"], // Reduced from 6 weights — saves ~100KB
  fallback: ["system-ui", "arial"],
});

export const metadata: Metadata = {
  title: {
    default: "Bandhan AI - Find Your Perfect Match",
    template: "%s | Bandhan AI",
  },
  description:
    "Bandhan AI uses artificial intelligence to help you find meaningful connections. Experience premium matchmaking designed for modern Indians.",
  keywords: [
    "matchmaking",
    "dating",
    "AI matchmaking",
    "Indian dating",
    "relationships",
    "bandhan",
    "shaadi",
    "matrimony",
    "love",
    "compatibility",
  ],
  authors: [{ name: "Bandhan AI Team" }],
  creator: "Bandhan AI",
  publisher: "Bandhan AI",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  metadataBase: new URL(process.env.NEXT_PUBLIC_APP_URL || "https://bandhan.ai"),
  openGraph: {
    type: "website",
    locale: "en_IN",
    url: "/",
    siteName: "Bandhan AI",
    title: "Bandhan AI - Find Your Perfect Match",
    description:
      "AI-powered matchmaking for meaningful connections. Designed for modern Indians.",
    images: [
      {
        url: "/og-image.png",
        width: 1200,
        height: 630,
        alt: "Bandhan AI - Premium Matchmaking",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Bandhan AI - Find Your Perfect Match",
    description:
      "AI-powered matchmaking for meaningful connections. Designed for modern Indians.",
    creator: "@bandhanai",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  icons: {
    icon: "/favicon.ico",
    apple: "/apple-touch-icon.png",
  },
  manifest: "/manifest.json",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${inter.variable} ${roboto.variable} ${comicNeue.variable} ${notoSansDevanagari.variable}`}
    >
      <head>
        {/* ── iOS PWA Support ────────────────────────────────────── */}
        {/* Tells iOS Safari this site can run as a standalone app */}
        <meta name="apple-mobile-web-app-capable" content="yes" />
        {/* Status bar: black-translucent = content extends under status bar */}
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
        <meta name="apple-mobile-web-app-title" content="Bandhan AI" />
        {/* Apple touch icon (180x180) — generated by scripts/generate-icons.mjs */}
        <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
        {/* iOS splash screens (launch images) */}
        {/* iPhone 14 Pro Max (430x932) */}
        <link
          rel="apple-touch-startup-image"
          href="/icons/icon-512x512.png"
          media="(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3)"
        />
        {/* iPhone 13/14 (390x844) */}
        <link
          rel="apple-touch-startup-image"
          href="/icons/icon-512x512.png"
          media="(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3)"
        />
        {/* iPhone SE (375x667) */}
        <link
          rel="apple-touch-startup-image"
          href="/icons/icon-512x512.png"
          media="(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2)"
        />
        {/* ── Theme colour (matches Navbar charcoal) ──────────── */}
        <meta name="theme-color" content="#212121" />
        {/* ── Manifest (linked in metadata too, but explicit for older browsers) */}
        <link rel="manifest" href="/manifest.json" />
      </head>
      <body
        className={`${roboto.className} text-[#212121]`}
        style={{
          backgroundColor: "#FFFFFF",
          backgroundImage:
            "repeating-linear-gradient(0deg, transparent, transparent 15px, rgba(0,0,0,0.015) 15px, rgba(0,0,0,0.015) 16px), repeating-linear-gradient(90deg, transparent, transparent 15px, rgba(0,0,0,0.015) 15px, rgba(0,0,0,0.015) 16px)",
        }}
      >
        <A11ySkipLink />
        <PerfInit />
        <LanguageProvider defaultLanguage="en">
          <AuthProvider>
            <AppShell>
              <main id="main-content" tabIndex={-1} className="outline-none">
                {children}
              </main>
            </AppShell>
            <InstallPrompt />
            <ConsentBanner />
          </AuthProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}
